name: 13 - Using Cache
on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        default: true
        description: Whether to execute cache step
      node-version:
        type: choice
        options: [18.x, 20.x, 21.x]
        default: 20.x
        description: Node version

jobs:
  install-deps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app/
    outputs:
      deps-cache-key: ${{ steps.cache-key.outputs.CACHE-KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Calculate cache key
        id: cache-key
        run: |
          echo "CACHE-KEY=deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}" >> "$GITHUB_OUTPUT"   

      - name: Download cached dependencies
        id: cache
        if: ${{ inputs.use-cache }}
        uses: actions/cache@v3
        with:
          key: ${{ steps.cache-key.outputs.cache-key }}
          path: 13-caching/react-app/node_modules 

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app/
    needs: 
      - install-deps
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Download cached dependencies
        id: cache
        uses: actions/cache@v3
        with:
          key: ${{ needs.install-deps.outputs.deps-cache-key }}
          path: 13-caching/react-app/node_modules

      - name: Testing
        run: npm run test

      - name: Building
        run: npm run build
      
      - name: Deploying to nonprod
        run: echo "Deploying to nonprod"

  linting:
    runs-on: ubuntu-latest
    needs:
      - install-deps
    defaults:
      run:
        working-directory: 13-caching/react-app/
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Download cached dependencies
        id: cache
        uses: actions/cache@v3
        with:
          key: ${{ needs.install-deps.outputs.deps-cache-key }}
          path: 13-caching/react-app/node_modules 

      - name: Testing
        run: npm run test

      - name: Linting
        run: echo "Linting..."
    
    
