name: 17 - 3 - Custom Actions - Docker

on:
  workflow_dispatch:
    inputs:
      url:
        type: choice
        description: URL to ping
        options: ['https://www.google.com', 'htt://www.googletastic.com']
      max_attempts:
        required: false
        description: Maximum number of attempts until action fails
        default: '10'
      delay:
        required: false
        description: Delay in seconds between attempts
        default: '5'

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{ inputs.url }}
          max_attempts: ${{ inputs.max_attempts }}
          delay: ${{ inputs.delay }}
